USE discord_bot;
-- NUOVE COLONNE PER I BADGE VIDEO/STREAM
ALTER TABLE users
ADD COLUMN IF NOT EXISTS video_seconds INT DEFAULT 0;
ALTER TABLE users
ADD COLUMN IF NOT EXISTS stream_seconds INT DEFAULT 0;